# This is a basic workflow to help you get started with Actions

name: Generate Installer

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  release:
    types: [ published ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "geninstaller"
  geninstaller:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Creates installer
      - name: Generate installer
        run: ./geninstaller

      # Uploads installer as artefact
      - name: Upload artefact
        uses: actions/upload-artifact@v2
        with:
          path: installshaber
      
      # Uploads installer to release
      - name: Upload to release
        uses: AButler/upload-release-assets@v2.0
        with:
          files: installshaber
          repo-token: ${{ secrets.GITHUB_TOKEN }}
